# Generated by Django 5.1.1 on 2024-09-25 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=128)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField()),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_list.tag')),
            ],
        ),
    ]
