# Generated by Django 5.1.1 on 2024-09-25 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_alter_task_options_remove_task_tag_task_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='tag',
            new_name='tags',
        ),
    ]
